export const parkAppModule = {
    _id: "801955773415604",
    homeList: [{
            bindTableId: "0",
            bindTableName: "",
            iconUrl: "iconfont icon-qixiangtubiao-wubeijing- color-8",
            id: "645534670766780416",
            isValid: true,
            layer: 3,
            miniRouteKey: "",
            moduleCode: "",
            moduleName: "天气",
            openType: 0,
            ownerId: "801955773415604",
            ownerType: 3,
            parentId: "645534670712254464",
            path: ",0,1,2,645534670712254464,",
            refferId: "6",
            remarks: "1",
            routeKey: "/api-tools/pages/weather/weather",
            sceneType: 0,
            sequence: 1,
        },
        {
            bindTableId: "0",
            bindTableName: "",
            iconUrl: "iconfont icon-yiqingguanli color-6",
            id: "645534670779363328",
            isValid: true,
            layer: 3,
            miniRouteKey: "",
            moduleCode: "",
            moduleName: "防疫政策查询",
            openType: 0,
            ownerId: "801955773415604",
            ownerType: 3,
            parentId: "645534670712254464",
            path: ",0,1,2,645534670712254464,",
            refferId: "14",
            remarks: "",
            routeKey: "/api-tools/pages/bankExchangeRate/bankExchangeRate",
            sceneType: 0,
            sequence: 3,
        },
        {
            bindTableId: "0",
            bindTableName: "",
            iconUrl: "iconfont icon-rank color-7",
            id: "645534670770974720",
            isValid: true,
            layer: 3,
            miniRouteKey: "",
            moduleCode: "",
            moduleName: "奥运奖牌榜",
            openType: 0,
            ownerId: "801955773415604",
            ownerType: 3,
            parentId: "645534670712254464",
            path: ",0,1,2,645534670712254464,",
            refferId: "13",
            remarks: "",
            routeKey: "/api-tools/pages/OlyMedals/OlyMedals",
            sceneType: 0,
            sequence: 4,
        },
        {
            bindTableId: "0",
            bindTableName: "",
            iconUrl: "iconfont icon-shanzhao color-8",
            id: "645534670787751936",
            isValid: true,
            layer: 3,
            miniRouteKey: "",
            moduleCode: "",
            moduleName: "我要爆照",
            openType: 0,
            ownerId: "801955773415604",
            ownerType: 3,
            parentId: "645534670712254464",
            path: ",0,1,2,645534670712254464,",
            refferId: "15",
            remarks: "",
            routeKey: "/api-ai/category/manage",
            sceneType: 0,
            sequence: 2,
        },
        {
            bindTableId: "0",
            bindTableName: "",
            iconUrl: "iconfont icon-shanzhao color-5",
            id: "645534670770974720",
            isValid: true,
            layer: 3,
            miniRouteKey: "",
            moduleCode: "",
            moduleName: "头像一键生成",
            openType: 0,
            ownerId: "801955773415604",
            ownerType: 3,
            parentId: "645534670712254464",
            path: ",0,1,2,645534670712254464,",
            refferId: "13",
            remarks: "",
            routeKey: "/api-toolkit/pages/christmasHat/index/index",
            sceneType: 0,
            sequence: 4,
        },
    ],
    name: "张江科技园",
    serviceList: [{
            bindTableId: "0",
            bindTableName: "",
            children: [{
                    bindTableId: "0",
                    bindTableName: "",
                    iconUrl: "iconfont icon-cidianku color-1",
                    id: "645534670766780416",
                    isValid: true,
                    layer: 3,
                    miniRouteKey: "",
                    moduleCode: "",
                    moduleName: "成语查询",
                    openType: 0,
                    ownerId: "801955773415604",
                    ownerType: 3,
                    parentId: "645534670712254464",
                    path: ",0,1,2,645534670712254464,",
                    refferId: "6",
                    remarks: "1",
                    routeKey: "/api-tools/pages/idiomQuery/idiomQuery",
                    sceneType: 0,
                    sequence: 1,
                },
                {
                    bindTableId: "0",
                    bindTableName: "",
                    iconUrl: "iconfont icon-zidianguanli color-2",
                    id: "645534670787751936",
                    isValid: true,
                    layer: 3,
                    miniRouteKey: "",
                    moduleCode: "",
                    moduleName: "新华字典",
                    openType: 0,
                    ownerId: "801955773415604",
                    ownerType: 3,
                    parentId: "645534670712254464",
                    path: ",0,1,2,645534670712254464,",
                    refferId: "15",
                    remarks: "",
                    routeKey: "/api-tools/pages/xinhuaDictionary/xinhuaDictionary",
                    sceneType: 0,
                    sequence: 2,
                },
                {
                    bindTableId: "0",
                    bindTableName: "",
                    iconUrl: "iconfont icon-pinyinzhuanhua color-3",
                    id: "645534670779363328",
                    isValid: true,
                    layer: 3,
                    miniRouteKey: "",
                    moduleCode: "",
                    moduleName: "查拼音",
                    openType: 0,
                    ownerId: "801955773415604",
                    ownerType: 3,
                    parentId: "645534670712254464",
                    path: ",0,1,2,645534670712254464,",
                    refferId: "14",
                    remarks: "",
                    routeKey: "/api-tools/pages/pinyin/index",
                    sceneType: 0,
                    sequence: 3,
                },
                {
                    bindTableId: "0",
                    bindTableName: "",
                    iconUrl: "iconfont icon-riyu color-4",
                    id: "645534670770974720",
                    isValid: true,
                    layer: 3,
                    miniRouteKey: "",
                    moduleCode: "",
                    moduleName: "五十音图",
                    openType: 0,
                    ownerId: "801955773415604",
                    ownerType: 3,
                    parentId: "645534670712254464",
                    path: ",0,1,2,645534670712254464,",
                    refferId: "13",
                    remarks: "",
                    routeKey: "/api-tools/pages/gojuuonn/gojuuonn",
                    sceneType: 0,
                    sequence: 4,
                },
            ],
            iconUrl: "icon icon-xiangmu color-7",
            id: "645534670712254464",
            isValid: true,
            layer: 2,
            miniRouteKey: "",
            moduleCode: "",
            moduleName: "学习助手",
            openType: 0,
            ownerId: "801955773415604",
            ownerType: 3,
            parentId: "2",
            path: ",0,1,2,",
            refferId: "3",
            remarks: "",
            routeKey: "",
            sceneType: 0,
            sequence: 1,
        },
        {
            bindTableId: "0",
            bindTableName: "",
            children: [{
                    bindTableId: "0",
                    bindTableName: "",
                    iconUrl: "iconfont icon-qixiangtubiao-wubeijing- color-8",
                    id: "683978618833022976",
                    isValid: true,
                    layer: 3,
                    miniRouteKey: "",
                    moduleCode: "",
                    moduleName: "天气",
                    openType: 0,
                    ownerId: "801955773415604",
                    ownerType: 3,
                    parentId: "683978618757525504",
                    path: ",0,1,2,683978618757525504,",
                    refferId: "25",
                    remarks: "",
                    routeKey: "/api-tools/pages/weather/weather",
                    sceneType: 0,
                    sequence: 1,
                },
                {
                    bindTableId: "0",
                    bindTableName: "",
                    iconUrl: "iconfont icon-erweima color-7",
                    id: "683978618824634368",
                    isValid: true,
                    layer: 3,
                    miniRouteKey: "",
                    moduleCode: "",
                    moduleName: "二维码生成器",
                    openType: 0,
                    ownerId: "801955773415604",
                    ownerType: 3,
                    parentId: "683978618757525504",
                    path: ",0,1,2,683978618757525504,",
                    refferId: "24",
                    remarks: "",
                    routeKey: "/api-tools/pages/qrcodeGenerate/qrcodeGenerate",
                    sceneType: 0,
                    sequence: 2,
                },
                {
                    bindTableId: "0",
                    bindTableName: "",
                    iconUrl: "iconfont icon-huangli color-3",
                    id: "683978618820440064",
                    isValid: true,
                    layer: 3,
                    miniRouteKey: "",
                    moduleCode: "",
                    moduleName: "万年历",
                    openType: 0,
                    ownerId: "801955773415604",
                    ownerType: 3,
                    parentId: "683978618757525504",
                    path: ",0,1,2,683978618757525504,",
                    refferId: "23",
                    remarks: "",
                    routeKey: "/api-tools/pages/perpetualCalendar/index",
                    sceneType: 0,
                    sequence: 3,
                },
                {
                    bindTableId: "0",
                    bindTableName: "",
                    iconUrl: "iconfont icon-jiaqitebieriqi color-4",
                    id: "683978618841411584",
                    isValid: true,
                    layer: 3,
                    miniRouteKey: "",
                    moduleCode: "",
                    moduleName: "假期列表",
                    openType: 0,
                    ownerId: "801955773415604",
                    ownerType: 3,
                    parentId: "683978618757525504",
                    path: ",0,1,2,683978618757525504,",
                    refferId: "27",
                    remarks: "",
                    routeKey: "/api-tools/pages/holidayList/holidayList",
                    sceneType: 0,
                    sequence: 4,
                },
                {
                    bindTableId: "0",
                    bindTableName: "",
                    iconUrl: "iconfont icon-huangli color-2",
                    id: "683978618837217280",
                    isValid: true,
                    layer: 3,
                    miniRouteKey: "",
                    moduleCode: "",
                    moduleName: "程序员黄历",
                    openType: 0,
                    ownerId: "801955773415604",
                    ownerType: 3,
                    parentId: "683978618757525504",
                    path: ",0,1,2,683978618757525504,",
                    refferId: "26",
                    remarks: "",
                    routeKey: "/api-tools/pages/cand/index",
                    sceneType: 0,
                    sequence: 5,
                },
                {
                    bindTableId: "0",
                    bindTableName: "",
                    iconUrl: "iconfont icon-shengao color-9",
                    id: "683978618812051456",
                    isValid: true,
                    layer: 3,
                    miniRouteKey: "",
                    moduleCode: "",
                    moduleName: "身材计算",
                    openType: 0,
                    ownerId: "801955773415604",
                    ownerType: 3,
                    parentId: "683978618757525504",
                    path: ",0,1,2,683978618757525504,",
                    refferId: "21",
                    remarks: "",
                    routeKey: "/api-tools/pages/figure/figure",
                    sceneType: 0,
                    sequence: 6,
                },
                {
                    bindTableId: "0",
                    bindTableName: "",
                    iconUrl: "iconfont icon-shebao color-10",
                    id: "683978618816245760",
                    isValid: true,
                    layer: 3,
                    miniRouteKey: "",
                    moduleCode: "",
                    moduleName: "五险一金计算",
                    openType: 0,
                    ownerId: "801955773415604",
                    ownerType: 3,
                    parentId: "683978618757525504",
                    path: ",0,1,2,683978618757525504,",
                    refferId: "22",
                    remarks: "",
                    routeKey: "/api-tools/pages/calculate/calculate",
                    sceneType: 0,
                    sequence: 7,
                },
                {
                    bindTableId: "0",
                    bindTableName: "",
                    iconUrl: "iconfont icon-jisuanqi color-1",
                    id: "683978618845605888",
                    isValid: true,
                    layer: 3,
                    miniRouteKey: "",
                    moduleCode: "",
                    moduleName: "计算器",
                    openType: 0,
                    ownerId: "801955773415604",
                    ownerType: 3,
                    parentId: "683978618757525504",
                    path: ",0,1,2,683978618757525504,",
                    refferId: "28",
                    remarks: "",
                    routeKey: "/api-tools/pages/calculator-index/index",
                    sceneType: 0,
                    sequence: 8,
                },
            ],
            iconUrl: "icon icon-xiangmu color-7",
            id: "683978618757525504",
            isValid: true,
            layer: 2,
            miniRouteKey: "",
            moduleCode: "",
            moduleName: "效率工具",
            openType: 0,
            ownerId: "801955773415604",
            ownerType: 3,
            parentId: "2",
            path: ",0,1,2,",
            refferId: "5",
            remarks: "",
            routeKey: "",
            sceneType: 0,
            sequence: 2,
        },
        {
            bindTableId: "0",
            bindTableName: "",
            children: [{
                    bindTableId: "0",
                    bindTableName: "",
                    iconUrl: "iconfont icon-IPdizhi color-5",
                    id: "675898647040249856",
                    isValid: true,
                    layer: 3,
                    miniRouteKey: "",
                    moduleCode: "",
                    moduleName: "IP查询",
                    openType: 0,
                    ownerId: "801955773415604",
                    ownerType: 3,
                    parentId: "675898646989918208",
                    path: ",0,1,2,675898646989918208,",
                    refferId: "1841441760346153",
                    remarks: "",
                    routeKey: "/api-tools/pages/IP/IP",
                    sceneType: 0,
                    sequence: 1,
                },
                {
                    bindTableId: "0",
                    bindTableName: "",
                    iconUrl: "iconfont icon-shoujihao color-6",
                    id: "675898647036055552",
                    isValid: true,
                    layer: 3,
                    miniRouteKey: "",
                    moduleCode: "",
                    moduleName: "手机归属地",
                    openType: 0,
                    ownerId: "801955773415604",
                    ownerType: 3,
                    parentId: "675898646989918208",
                    path: ",0,1,2,675898646989918208,",
                    refferId: "1841441441579176",
                    remarks: "",
                    routeKey: "/api-tools/pages/MobileHome/MobileHome",
                    sceneType: 0,
                    sequence: 2,
                },
                {
                    bindTableId: "0",
                    bindTableName: "",
                    iconUrl: "iconfont icon-yiqingguanli color-6",
                    id: "675898647031861248",
                    isValid: true,
                    layer: 3,
                    miniRouteKey: "",
                    moduleCode: "",
                    moduleName: "防疫政策查询",
                    openType: 0,
                    ownerId: "801955773415604",
                    ownerType: 3,
                    parentId: "675898646989918208",
                    path: ",0,1,2,675898646989918208,",
                    refferId: "1841441122811963",
                    remarks: "",
                    routeKey: "/api-tools/pages/bankExchangeRate/bankExchangeRate",
                    sceneType: 0,
                    sequence: 3,
                },
                {
                    bindTableId: "0",
                    bindTableName: "",
                    iconUrl: "iconfont icon-fengxian color-5",
                    id: "675898647065415680",
                    isValid: true,
                    layer: 3,
                    miniRouteKey: "",
                    moduleCode: "",
                    moduleName: "中高风险地区",
                    openType: 0,
                    ownerId: "801955773415604",
                    ownerType: 3,
                    parentId: "675898646989918208",
                    path: ",0,1,2,675898646989918208,",
                    refferId: "1841442431434913",
                    remarks: "",
                    routeKey: "/api-tools/pages/horoscope/horoscope",
                    sceneType: 0,
                    sequence: 4,
                },
            ],
            iconUrl: "icon icon-xiangmu color-7",
            id: "675898646989918208",
            isValid: true,
            layer: 2,
            miniRouteKey: "",
            moduleCode: "ServiceProduct",
            moduleName: "查询服务",
            openType: 0,
            ownerId: "801955773415604",
            ownerType: 3,
            parentId: "2",
            path: ",0,1,2,",
            refferId: "1768943031156886",
            remarks: "",
            routeKey: "",
            sceneType: 0,
            sequence: 3,
        },
        {
            bindTableId: "0",
            bindTableName: "",
            children: [{
                    bindTableId: "0",
                    bindTableName: "",
                    iconUrl: "iconfont icon-rank color-7",
                    id: "675898647065415680",
                    isValid: true,
                    layer: 3,
                    miniRouteKey: "",
                    moduleCode: "",
                    moduleName: "奥运奖牌榜",
                    openType: 0,
                    ownerId: "801955773415604",
                    ownerType: 3,
                    parentId: "675898646989918208",
                    path: ",0,1,2,675898646989918208,",
                    refferId: "1841442431434913",
                    remarks: "",
                    routeKey: "/api-tools/pages/OlyMedals/OlyMedals",
                    sceneType: 0,
                    sequence: 4,
                },
                {
                    bindTableId: "0",
                    bindTableName: "",
                    iconUrl: "iconfont icon-shanzhao color-8",
                    id: "645534671010050048",
                    isValid: true,
                    layer: 3,
                    miniRouteKey: "",
                    moduleCode: "",
                    moduleName: "我要爆照",
                    openType: 0,
                    ownerId: "801955773415604",
                    ownerType: 3,
                    parentId: "645534670993272832",
                    path: ",0,1,2,645534670993272832,",
                    refferId: "17",
                    remarks: "",
                    routeKey: "/api-ai/category/manage",
                    sceneType: 0,
                    sequence: 1,
                },
                {
                    bindTableId: "0",
                    bindTableName: "",
                    iconUrl: "iconfont icon-shanzhao color-5",
                    id: "645534670770974720",
                    isValid: true,
                    layer: 3,
                    miniRouteKey: "",
                    moduleCode: "",
                    moduleName: "头像一键生成",
                    openType: 0,
                    ownerId: "801955773415604",
                    ownerType: 3,
                    parentId: "645534670712254464",
                    path: ",0,1,2,645534670712254464,",
                    refferId: "13",
                    remarks: "",
                    routeKey: "/api-toolkit/pages/christmasHat/index/index",
                    sceneType: 0,
                    sequence: 4,
                },
                {
                    bindTableId: "0",
                    bindTableName: "",
                    iconUrl: "iconfont icon-shanzhao color-8",
                    id: "645534671010050048",
                    isValid: true,
                    layer: 3,
                    miniRouteKey: "",
                    moduleCode: "",
                    moduleName: "手持弹幕",
                    openType: 0,
                    ownerId: "801955773415604",
                    ownerType: 3,
                    parentId: "645534670993272832",
                    path: ",0,1,2,645534670993272832,",
                    refferId: "17",
                    remarks: "",
                    routeKey: "/api-ai/danmu/index",
                    sceneType: 0,
                    sequence: 1,
                },
                {
                    bindTableId: "0",
                    bindTableName: "",
                    iconUrl: "iconfont icon-touzi color-9",
                    id: "645534671026827264",
                    isValid: true,
                    layer: 3,
                    miniRouteKey: "",
                    moduleCode: "",
                    moduleName: "摇骰子",
                    openType: 0,
                    ownerId: "801955773415604",
                    ownerType: 3,
                    parentId: "645534670993272832",
                    path: ",0,1,2,645534670993272832,",
                    refferId: "1904143383920648",
                    remarks: "",
                    routeKey: "/api-tools/pages/game/game",
                    sceneType: 0,
                    sequence: 2,
                },
                {
                    bindTableId: "0",
                    bindTableName: "",
                    iconUrl: "iconfont icon-2048 color-10",
                    id: "645534671014244352",
                    isValid: true,
                    layer: 3,
                    miniRouteKey: "",
                    moduleCode: "",
                    moduleName: "2048",
                    openType: 0,
                    ownerId: "801955773415604",
                    ownerType: 3,
                    parentId: "645534670993272832",
                    path: ",0,1,2,645534670993272832,",
                    refferId: "19",
                    remarks: "",
                    routeKey: "/api-tools/pages/2048/2048",
                    sceneType: 0,
                    sequence: 3,
                },
            ],
            iconUrl: "icon icon-xiangmu color-7",
            id: "645534670993272832",
            isValid: true,
            layer: 2,
            miniRouteKey: "",
            moduleCode: "",
            moduleName: "轻松一下",
            openType: 0,
            ownerId: "801955773415604",
            ownerType: 3,
            parentId: "2",
            path: ",0,1,2,",
            refferId: "4",
            remarks: "",
            routeKey: "",
            sceneType: 0,
            sequence: 4,
        },
    ],
};

export const server = [{
        img: "iconfont icon-cidianku color-1",
        openpath: "/api-tools/pages/idiomQuery/idiomQuery",
        text: "成语查询",
    },
    {
        img: "iconfont icon-zidianguanli color-2",
        openpath: "/api-tools/pages/xinhuaDictionary/xinhuaDictionary",
        text: "新华字典",
    },
    {
        img: "iconfont icon-pinyinzhuanhua color-3",
        openpath: "/api-tools/pages/pinyin/index",
        text: "查拼音",
    },
    {
        img: "iconfont icon-riyu color-4",
        openpath: "/api-tools/pages/gojuuonn/gojuuonn",
        text: "五十音图",
    },
    {
        img: "iconfont icon-IPdizhi color-5",
        openpath: "/api-tools/pages/IP/IP",
        text: "IP查询",
    },
    {
        img: "iconfont icon-shoujihao color-6",
        openpath: "/api-tools/pages/MobileHome/MobileHome",
        text: "手机归属地",
    },
    {
        img: "iconfont icon-erweima color-7",
        openpath: "/api-tools/pages/qrcodeGenerate/qrcodeGenerate",
        text: "二维码生成器",
    },
    {
        img: "iconfont icon-qixiangtubiao-wubeijing- color-8",
        openpath: "/api-tools/pages/weather/weather",
        text: "天气",
    },
    {
        img: "iconfont icon-shengao color-9",
        openpath: "/api-tools/pages/figure/figure",
        text: "身材计算",
    },
    {
        img: "iconfont icon-shebao color-10",
        openpath: "/api-tools/pages/calculate/calculate",
        text: "五险一金计算",
    },
    {
        img: "iconfont icon-jisuanqi color-1",
        openpath: "/api-tools/pages/calculator-index/index",
        text: "计算器",
    },
    {
        img: "iconfont icon-huangli color-2",
        openpath: "/api-tools/pages/cand/index",
        text: "程序员黄历",
    },
    {
        img: "iconfont icon-huangli color-3",
        openpath: "/api-tools/pages/perpetualCalendar/index",
        text: "万年历",
    },
    {
        img: "iconfont icon-jiaqitebieriqi color-4",
        openpath: "/api-tools/pages/holidayList/holidayList",
        text: "假期列表",
    },
    {
        img: "iconfont icon-fengxian color-5",
        openpath: "/api-tools/pages/horoscope/horoscope",
        text: "中高风险地区",
    },
    {
        img: "iconfont icon-yiqingguanli color-6",
        openpath: "/api-tools/pages/bankExchangeRate/bankExchangeRate",
        text: "防疫政策查询",
    },
    {
        img: "iconfont icon-rank color-7",
        openpath: "/api-tools/pages/OlyMedals/OlyMedals",
        text: "奥运奖牌榜",
    },
    {
        img: "iconfont icon-shanzhao color-8",
        openpath: "/api-ai/category/manage",
        text: "我要爆照",
    },
    {
        img: "iconfont icon-touzi color-9",
        openpath: "/api-tools/pages/game/game",
        text: "摇骰子",
    },
    {
        img: "iconfont icon-2048 color-10",
        openpath: "/api-tools/pages/2048/2048",
        text: "2048",
    },
];

export const parkHomeModule = [{
        bindTableId: "0",
        bindTableName: "",
        iconUrl: "iconfont icon-qixiangtubiao-wubeijing- color-8",
        id: "645534670766780416",
        isValid: true,
        layer: 3,
        miniRouteKey: "",
        moduleCode: "",
        moduleName: "天气",
        openType: 0,
        ownerId: "801955773415604",
        ownerType: 3,
        parentId: "645534670712254464",
        path: ",0,1,2,645534670712254464,",
        refferId: "6",
        remarks: "1",
        routeKey: "/api-tools/pages/weather/weather",
        sceneType: 0,
        sequence: 1,
    },
    {
        bindTableId: "0",
        bindTableName: "",
        iconUrl: "iconfont icon-yiqingguanli color-6",
        id: "645534670779363328",
        isValid: true,
        layer: 3,
        miniRouteKey: "",
        moduleCode: "",
        moduleName: "防疫政策查询",
        openType: 0,
        ownerId: "801955773415604",
        ownerType: 3,
        parentId: "645534670712254464",
        path: ",0,1,2,645534670712254464,",
        refferId: "14",
        remarks: "",
        routeKey: "/api-tools/pages/bankExchangeRate/bankExchangeRate",
        sceneType: 0,
        sequence: 3,
    },
    {
        bindTableId: "0",
        bindTableName: "",
        iconUrl: "iconfont icon-rank color-7",
        id: "645534670770974720",
        isValid: true,
        layer: 3,
        miniRouteKey: "",
        moduleCode: "",
        moduleName: "奥运奖牌榜",
        openType: 0,
        ownerId: "801955773415604",
        ownerType: 3,
        parentId: "645534670712254464",
        path: ",0,1,2,645534670712254464,",
        refferId: "13",
        remarks: "",
        routeKey: "/api-tools/pages/OlyMedals/OlyMedals",
        sceneType: 0,
        sequence: 4,
    },
    {
        bindTableId: "0",
        bindTableName: "",
        iconUrl: "iconfont icon-shanzhao color-8",
        id: "645534670787751936",
        isValid: true,
        layer: 3,
        miniRouteKey: "",
        moduleCode: "",
        moduleName: "我要爆照",
        openType: 0,
        ownerId: "801955773415604",
        ownerType: 3,
        parentId: "645534670712254464",
        path: ",0,1,2,645534670712254464,",
        refferId: "15",
        remarks: "",
        routeKey: "/api-ai/category/manage",
        sceneType: 0,
        sequence: 2,
    },
];